language: php

env:
  global:
    - APP_ENV=testing

# list any PHP version you want to test against
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist --no-interaction

script: vendor/bin/phpunit
